language: android
jdk: oraclejdk8
android:
components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - tools
    # - platform-tools

    # The BuildTools version used by your project
    - tools
    - platform-tools
    - build-tools-23.0.1
    - android-25

licenses:
    - 'android-sdk-preview-license'
    - 'android-sdk-license'
