language: android
sudo: false
android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-25.0.2
    - tools
    - android-25
    # The BuildTools version used by your project
    #- build-tools-19.1.0
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

jdk: oraclejdk8
os:
  - linux

before_script:
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &