language: android
sudo: false
android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-25.0.2
    - tools
    - android-25
    # The BuildTools version used by your project
    #- build-tools-19.1.0
jdk: oraclejdk8
os:
  - linux